using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Windows.Forms;

static class CustomThemes {
 public const int Limit=12;
 public static List<PonyTheme> Load(string directory){var result=new List<PonyTheme>();string folder=Path.Combine(directory,"uploads");if(!Directory.Exists(folder))return result;var files=Directory.GetFiles(folder,"custom-*.png");Array.Sort(files,StringComparer.Ordinal);Array.Reverse(files);foreach(string file in files){try{result.Add(Read(file));}catch(Exception){}}return result;}
 static PonyTheme Read(string file){using(var image=new Bitmap(file)){var t=Make(image,Path.GetFileNameWithoutExtension(file));t.IconFile=Path.ChangeExtension(file,".ico");if(!File.Exists(t.IconFile))SaveIcon(image,t.IconFile);using(var icon=new Icon(t.IconFile))t.Icon=(Icon)icon.Clone();return t;}}
 static Color Hsv(float hue,double saturation,double value){double h=hue/60;int sector=(int)h;double f=h-sector,p=value*(1-saturation),q=value*(1-f*saturation),t=value*(1-(1-f)*saturation);double r=value,g=t,b=p;switch(sector%6){case 1:r=q;g=value;b=p;break;case 2:r=p;g=value;b=t;break;case 3:r=p;g=q;b=value;break;case 4:r=t;g=p;b=value;break;case 5:r=value;g=p;b=q;break;}return Color.FromArgb((int)(255*r),(int)(255*g),(int)(255*b));}
 static PonyTheme Make(Bitmap image,string id){double[] votes=new double[24];double saturation=0;int n=0;for(int y=0;y<image.Height;y+=8)for(int x=0;x<image.Width;x+=8){Color c=image.GetPixel(x,y);if(c.A<128)continue;double s=c.GetSaturation();if(c.GetBrightness()<.12||c.GetBrightness()>.94)continue;votes[Math.Min(23,(int)(c.GetHue()/15))]+=s*s;saturation+=s;n++;}int best=0;for(int i=1;i<24;i++)if(votes[i]>votes[best])best=i;float hue=best*15+7;bool neutral=n==0||saturation/n<.08;Color bubble=neutral?Color.FromArgb(235,222,244):Hsv(hue,.48,.98);var theme=new PonyTheme(id,"我的图片","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF");theme.Bubble=bubble;theme.Glyph=Color.FromArgb(255,251,215);theme.Ink=neutral?Color.FromArgb(66,40,81):Hsv(hue,.75,.26);theme.Accent=neutral?Color.FromArgb(131,73,164):Hsv(hue,.75,.46);theme.Page=Color.FromArgb(255,(bubble.R+2295)/10,(bubble.G+2295)/10,(bubble.B+2295)/10);theme.Picture=new Bitmap(image);return theme;}
 public static PonyTheme Import(string path,string directory){var info=new FileInfo(path);if(info.Length>40*1024*1024)throw new InvalidOperationException("请选择小于 40 MB 的图片。");string folder=Path.Combine(directory,"uploads");Directory.CreateDirectory(folder);string id="custom-"+DateTime.UtcNow.Ticks.ToString("D19")+"-"+Guid.NewGuid().ToString("N");string file=Path.Combine(folder,id+".png");try{using(var source=Image.FromFile(path)){if((long)source.Width*source.Height>40000000)throw new InvalidOperationException("图片尺寸过大，请选择不超过 4000 万像素的图片。");try{int orientation=source.GetPropertyItem(0x112).Value[0];RotateFlipType[] rotations={RotateFlipType.RotateNoneFlipNone,RotateFlipType.RotateNoneFlipNone,RotateFlipType.RotateNoneFlipX,RotateFlipType.Rotate180FlipNone,RotateFlipType.Rotate180FlipX,RotateFlipType.Rotate90FlipX,RotateFlipType.Rotate90FlipNone,RotateFlipType.Rotate270FlipX,RotateFlipType.Rotate270FlipNone};if(orientation<rotations.Length)source.RotateFlip(rotations[orientation]);}catch(ArgumentException){}using(var square=new Bitmap(512,512)){using(var g=Graphics.FromImage(square)){g.Clear(Color.White);g.InterpolationMode=InterpolationMode.HighQualityBicubic;int side=Math.Min(source.Width,source.Height);g.DrawImage(source,new Rectangle(0,0,512,512),new Rectangle((source.Width-side)/2,(source.Height-side)/2,side,side),GraphicsUnit.Pixel);}square.Save(file,ImageFormat.Png);SaveIcon(square,Path.ChangeExtension(file,".ico"));}}return Read(file);}catch{if(File.Exists(file))File.Delete(file);string icon=Path.ChangeExtension(file,".ico");if(File.Exists(icon))File.Delete(icon);throw;}}
 public static void Prune(string directory,string selected){string folder=Path.Combine(directory,"uploads");if(!Directory.Exists(folder))return;var files=new List<string>(Directory.GetFiles(folder,"custom-*.png"));files.Sort(StringComparer.Ordinal);while(files.Count>Limit){string file=files.Find(f=>Path.GetFileNameWithoutExtension(f)!=selected);if(file==null)break;File.Delete(file);string icon=Path.ChangeExtension(file,".ico");if(File.Exists(icon))File.Delete(icon);files.Remove(file);}}
 public static void SaveIcon(Image source,string path){int[] sizes={16,24,32,48,64,128,256};var frames=new List<byte[]>();foreach(int size in sizes){using(var large=new Bitmap(size*4,size*4)){using(var g=Graphics.FromImage(large)){g.SmoothingMode=SmoothingMode.AntiAlias;using(var brush=new TextureBrush(source)){brush.ScaleTransform((float)large.Width/source.Width,(float)large.Height/source.Height);g.FillEllipse(brush,0,0,large.Width,large.Height);}}using(var small=new Bitmap(size,size)){using(var g=Graphics.FromImage(small)){g.InterpolationMode=InterpolationMode.HighQualityBicubic;g.DrawImage(large,0,0,size,size);}using(var memory=new MemoryStream()){small.Save(memory,ImageFormat.Png);frames.Add(memory.ToArray());}}}}using(var writer=new BinaryWriter(File.Create(path))){writer.Write((ushort)0);writer.Write((ushort)1);writer.Write((ushort)sizes.Length);int offset=6+16*sizes.Length;for(int i=0;i<sizes.Length;i++){writer.Write((byte)(sizes[i]==256?0:sizes[i]));writer.Write((byte)(sizes[i]==256?0:sizes[i]));writer.Write((ushort)0);writer.Write((ushort)1);writer.Write((ushort)32);writer.Write(frames[i].Length);writer.Write(offset);offset+=frames[i].Length;}foreach(var frame in frames)writer.Write(frame);}}
}

sealed class ImageThemePicker : Form {
 public PonyTheme Selected;
 public ImageThemePicker(PonyTheme current,string directory){SuspendLayout();AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;Text="选择角色或上传图片";Font=new Font("Microsoft YaHei UI",10);ClientSize=new Size(640,560);MinimumSize=new Size(600,400);StartPosition=FormStartPosition.CenterParent;BackColor=current.Page;Icon=current.Icon;
 var header=new Panel{Dock=DockStyle.Top,Height=84};var upload=new Button{Text="＋ 上传图片",Location=new Point(18,12),Size=new Size(150,34),BackColor=current.Bubble,FlatStyle=FlatStyle.Flat};header.Controls.Add(upload);header.Controls.Add(new Label{Text="保留最近 12 张 · 中心裁成圆形 · 自动搭配悬浮球颜色",AutoSize=true,Location=new Point(18,55)});upload.Click+=(s,e)=>{using(var dialog=new OpenFileDialog{Title="选择你喜欢的图片",Filter="图片|*.png;*.jpg;*.jpeg;*.bmp;*.gif",CheckFileExists=true}){if(dialog.ShowDialog(this)!=DialogResult.OK)return;try{Selected=CustomThemes.Import(dialog.FileName,directory);DialogResult=DialogResult.OK;}catch(Exception){MessageBox.Show(this,"图片未能导入，请选择有效的 PNG、JPG、BMP 或 GIF 图片（小于 40 MB、4000 万像素）。","无法导入图片");}}};
 var tabs=new TabControl{Dock=DockStyle.Fill};var builtins=new TabPage("七位角色");var uploads=new TabPage("我的图片（最多 12 张）");tabs.TabPages.Add(builtins);tabs.TabPages.Add(uploads);Populate(builtins,Themes.All,current);var saved=CustomThemes.Load(directory);Populate(uploads,saved.ToArray(),current);if(saved.Count==0)uploads.Controls.Add(new Label{Text="还没有上传图片，点击上方「上传图片」即可添加。",AutoSize=true,Location=new Point(20,25)});if(current.Id.StartsWith("custom-"))tabs.SelectedTab=uploads;Controls.Add(tabs);Controls.Add(header);ResumeLayout(true);}
 void Populate(TabPage page,PonyTheme[] themes,PonyTheme current){var flow=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,Padding=new Padding(8)};page.Controls.Add(flow);int index=0;foreach(var theme in themes){var chosen=theme;var image=new Bitmap(80,80);using(var g=Graphics.FromImage(image)){g.InterpolationMode=InterpolationMode.HighQualityBicubic;g.DrawImage(chosen.Picture,0,0,80,80);}var button=new Button{Size=new Size(136,130),Text=(chosen.Id.StartsWith("custom-")?"上传图片 "+(++index):chosen.Name)+(chosen.Id==current.Id?" ✓":""),Image=image,TextImageRelation=TextImageRelation.ImageAboveText,FlatStyle=FlatStyle.Flat,BackColor=chosen.Id==current.Id?chosen.Bubble:Color.White,ForeColor=chosen.Ink,Margin=new Padding(5)};button.Click+=(s,e)=>{Selected=chosen;DialogResult=DialogResult.OK;};button.Disposed+=(s,e)=>image.Dispose();flow.Controls.Add(button);}}
}
