using System;
using System.Drawing;
using System.Windows.Forms;

sealed partial class Reminder {
 TableLayoutPanel cardGrid;readonly Control[] reminderCards=new Control[3];int gridColumns;bool arranging;
 static TableLayoutPanel Stack(int columns){var panel=new TableLayoutPanel{AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,Dock=DockStyle.Top,ColumnCount=columns,Margin=new Padding(0)};for(int i=0;i<columns;i++)panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100f/columns));return panel;}
 static Label Caption(string text,Font font){return new Label{Text=text,Font=font,AutoSize=true,Anchor=AnchorStyles.Left,Margin=new Padding(3,6,3,6)};}
 static FlowLayoutPanel Flow(){return new FlowLayoutPanel{AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,Dock=DockStyle.Top,WrapContents=true,Margin=new Padding(0),Padding=new Padding(0,4,0,4)};}
 void BuildResponsiveUi(){
 SuspendLayout();AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;Font=new Font("Microsoft YaHei UI",10);Text="歇歇 · 远眺与起身舒展";Icon=theme.Icon;BackColor=theme.Page;ForeColor=theme.Ink;StartPosition=FormStartPosition.CenterScreen;ClientSize=new Size(820,760);MinimumSize=new Size(420,340);AutoScroll=true;
 var root=Stack(1);root.Padding=new Padding(20);Controls.Add(root);
 var head=Flow();avatar=new PictureBox{Image=theme.Picture,SizeMode=PictureBoxSizeMode.Zoom,Size=new Size(64,64),Margin=new Padding(0,0,12,0)};head.Controls.Add(avatar);var titles=Stack(1);titles.Dock=DockStyle.None;titles.AutoSize=true;titles.Controls.Add(Caption("歇歇",new Font(Font.FontFamily,24,FontStyle.Bold)));themeName=Caption(theme.Name+"陪你，慢慢来",new Font(Font.FontFamily,9));titles.Controls.Add(themeName);head.Controls.Add(titles);themeButton=MakeButton("角色 / 上传图片",170);themeButton.Click+=(s,e)=>ChooseTheme();head.Controls.Add(themeButton);root.Controls.Add(head);
 global=Caption("",Font);global.MaximumSize=new Size(700,0);root.Controls.Add(global);
 var summary=Flow();summary.BackColor=Color.White;summary.Padding=new Padding(12);var summaryText=Stack(1);summaryText.Dock=DockStyle.None;summaryText.Controls.Add(Caption("今日工作 / 专注",Font));today=Caption("0 分钟",new Font(Font.FontFamily,22,FontStyle.Bold));summaryText.Controls.Add(today);sessionLabel=Caption("",new Font(Font.FontFamily,9));summaryText.Controls.Add(sessionLabel);summary.Controls.Add(summaryText);var viewStats=MakeButton("查看周 / 月统计",160);viewStats.Click+=(s,e)=>ShowStatistics();summary.Controls.Add(viewStats);today.Cursor=Cursors.Hand;today.Click+=(s,e)=>ShowStatistics();root.Controls.Add(summary);
 cardGrid=Stack(1);root.Controls.Add(cardGrid);
 for(int i=0;i<3;i++){int index=i;var card=Stack(1);card.BackColor=Color.White;card.Padding=new Padding(12);card.Margin=new Padding(0,10,10,0);reminderCards[i]=card;
 var heading=Flow();heading.Controls.Add(Caption((i+1).ToString("00")+"  "+(i==0?"远眺放松":i==1?"起身舒展":""),new Font(Font,FontStyle.Bold)));if(i==2){customName=new TextBox{Text=store.CustomName,MaxLength=12,Width=180,Margin=new Padding(3,4,3,4)};customName.TextChanged+=(s,e)=>{if(initializing)return;store.CustomName=string.IsNullOrWhiteSpace(customName.Text)?"自定义":customName.Text.Trim();States[2].Name=store.CustomName;store.Changed();store.Save();Floating.Invalidate();};heading.Controls.Add(customName);}switches[i]=MakeButton("开启 / 继续",126);switches[i].Click+=(s,e)=>ToggleOne(index);heading.Controls.Add(switches[i]);card.Controls.Add(heading);
 var actionRow=Flow();counts[i]=Caption("00:00",new Font("Segoe UI",27,FontStyle.Bold));counts[i].MinimumSize=new Size(150,0);actionRow.Controls.Add(counts[i]);actions[i]=MakeButton("现在休息",130);actions[i].Click+=(s,e)=>Action(index);actionRow.Controls.Add(actions[i]);card.Controls.Add(actionRow);
 statuses[i]=Caption("",new Font(Font.FontFamily,9));card.Controls.Add(statuses[i]);
 var settings=Flow();settings.Controls.Add(Caption("每",Font));intervals[i]=new NumericUpDown{Minimum=1,Maximum=120,Width=64,Value=i==0?store.EyeMinutes:i==1?store.MoveMinutes:store.CustomMinutes,Margin=new Padding(3,5,3,3)};settings.Controls.Add(intervals[i]);settings.Controls.Add(Caption("分钟，休息",Font));durations[i]=new NumericUpDown{Minimum=i==0?20:1,Maximum=i==0?300:15,Width=64,Value=i==0?store.EyeSeconds:i==1?store.MoveSeconds/60:store.CustomSeconds/60,Margin=new Padding(3,5,3,3)};settings.Controls.Add(durations[i]);settings.Controls.Add(Caption(i==0?"秒":"分钟",Font));card.Controls.Add(settings);intervals[i].ValueChanged+=(s,e)=>SettingsChanged(index);durations[i].ValueChanged+=(s,e)=>SettingsChanged(index);cardGrid.Controls.Add(card,0,i);}
 var bar=Flow();pause=MakeButton("全部开启",125);pause.Click+=(s,e)=>Toggle();bar.Controls.Add(pause);var bubble=MakeButton("缩小为悬浮球",155);bubble.Click+=(s,e)=>FloatMode();bar.Controls.Add(bubble);var hide=MakeButton("最小化到托盘",155);hide.Click+=(s,e)=>{floatingMode=false;Floating.Hide();Hide();};bar.Controls.Add(hide);sound=new CheckBox{Text="提示音",AutoSize=true,Checked=store.Sound,Margin=new Padding(10,10,0,0)};sound.CheckedChanged+=(s,e)=>{store.Sound=sound.Checked;store.Changed();store.Save();};bar.Controls.Add(sound);root.Controls.Add(bar);
 var session=Flow();end=MakeButton("结束本次工作",155);end.Click+=(s,e)=>EndSession();session.Controls.Add(end);session.Controls.Add(Caption("暂停提醒也会累计时长；结束本次或关闭软件才停止。",new Font(Font.FontFamily,9)));root.Controls.Add(session);
 var footer=Flow();var info=new LinkLabel{Text="使用与健康建议",AutoSize=true,Margin=new Padding(3,8,12,8)};info.LinkClicked+=(s,e)=>ShowInfo();footer.Controls.Add(info);var license=new LinkLabel{Text="字体许可",AutoSize=true,Margin=new Padding(3,8,12,8)};license.LinkClicked+=(s,e)=>ShowLicense();footer.Controls.Add(license);var update=new LinkLabel{Text="更新与 GitHub",AutoSize=true,Margin=new Padding(3,8,12,8)};update.LinkClicked+=(s,e)=>Updates.Show(this,store.DirectoryPath);footer.Controls.Add(update);root.Controls.Add(footer);
 ClientSizeChanged+=(s,e)=>ArrangeCards();ResumeLayout(true);ArrangeCards();
 }
 internal void ArrangeCards(){if(arranging||cardGrid==null)return;arranging=true;try{float scale=Math.Max(CurrentAutoScaleDimensions.Width/96f,Font.Size/10f);int available=Math.Max(200,ClientSize.Width-(int)(60*scale));int columns=available/scale>=1120?3:available/scale>=760?2:1;cardGrid.SuspendLayout();if(columns!=gridColumns){gridColumns=columns;cardGrid.Controls.Clear();cardGrid.ColumnCount=columns;cardGrid.ColumnStyles.Clear();for(int i=0;i<columns;i++)cardGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100f/columns));cardGrid.RowCount=(3+columns-1)/columns;for(int i=0;i<3;i++)cardGrid.Controls.Add(reminderCards[i],i%columns,i/columns);}int textWidth=Math.Max(160,available/columns-(int)(40*scale));foreach(var label in statuses)if(label!=null)label.MaximumSize=new Size(textWidth,0);global.MaximumSize=new Size(available,0);sessionLabel.MaximumSize=new Size(Math.Max(180,available-(int)(25*scale)),0);cardGrid.ResumeLayout(true);}finally{arranging=false;}}
}
