using System;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Threading;
using System.Windows.Forms;

static class SelfTests {
 static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
 static object Field(object target,string name){return target.GetType().GetField(name,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public).GetValue(target);}
 static void Call(object target,string name,params object[] args){target.GetType().GetMethod(name,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public).Invoke(target,args);}
 static void Snapshot(Form form,string path){Application.DoEvents();using(var bmp=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bmp,new Rectangle(0,0,form.Width,form.Height));bmp.Save(path);}}
 static void CaptureFonts(Control root,System.Collections.Generic.Dictionary<Control,Font> fonts){fonts[root]=root.Font;foreach(Control child in root.Controls)CaptureFonts(child,fonts);}
 public static void Run(string folder){Directory.CreateDirectory(folder);string log=Path.Combine(folder,"tests.txt");File.WriteAllText(log,"");
 var clock=new ClockState(1200,20);Check(!clock.Tick(1199)&&clock.Tick(1)&&clock.Phase==1,"Reminder deadline");Check(!clock.Tick(100)&&clock.Phase==1,"Wait for confirmation");clock.Rest();Check(!clock.Tick(19)&&clock.Tick(1)&&clock.Phase==3,"Rest complete");clock.Reset();Check(clock.Left==1200&&clock.Phase==0,"Reset");
 string uploads=Path.Combine(folder,"uploads-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(uploads);string source=Path.Combine(uploads,"original.png");using(var sample=new Bitmap(160,100)){using(var g=Graphics.FromImage(sample))g.Clear(Color.DeepSkyBlue);sample.Save(source);}
 PonyTheme imported=CustomThemes.Import(source,uploads);Check(imported.Icon!=null&&imported.Picture.Width==512&&imported.Bubble.B>imported.Bubble.R,"Import icon and image palette");string first=imported.Id;for(int i=0;i<12;i++)imported=CustomThemes.Import(source,uploads);CustomThemes.Prune(uploads,imported.Id);Check(CustomThemes.Load(uploads).Count==12&&!File.Exists(Path.Combine(uploads,"uploads",first+".png"))&&File.Exists(source),"Retain twelve copies without deleting original");File.Delete(source);Check(CustomThemes.Load(uploads).Exists(t=>t.Id==imported.Id),"Copies survive missing originals");var uploadStore=new SessionStore(uploads);uploadStore.Theme=imported.Id;uploadStore.Changed();uploadStore.Save();using(var restored=new Reminder(uploads,false)){Check(((PonyTheme)Field(restored,"theme")).Id==imported.Id,"Restore uploaded theme after restart");restored.Close();}using(var picker=new ImageThemePicker(imported,uploads)){picker.Show();Snapshot(picker,Path.Combine(folder,"uploads-picker.png"));picker.Close();}File.WriteAllText(source,"invalid image");bool rejected=false;try{CustomThemes.Import(source,uploads);}catch{rejected=true;}Check(rejected&&CustomThemes.Load(uploads).Count==12,"Invalid input does not change gallery");File.AppendAllText(log,"PASS: uploaded image conversion, automatic palette, twelve-image retention, original independence, restart selection, invalid image rejection.\n");
 string data=Path.Combine(folder,"store-"+Guid.NewGuid().ToString("N"));var store=new SessionStore(data);DateTime midnight=new DateTime(2026,9,20,23,59,50,DateTimeKind.Local).ToUniversalTime();store.Start(midnight);store.Advance(midnight.AddSeconds(20));Check(Math.Abs(store.Total(new DateTime(2026,9,20))-10)<.001&&Math.Abs(store.Total(new DateTime(2026,9,21))-10)<.001,"Split at midnight");store.Advance(midnight.AddSeconds(50));Check(store.SessionSeconds==50,"Paused/rest/wait all included in session clock");store.End(midnight.AddSeconds(65));double total=store.Total(new DateTime(2026,9,21));store.Advance(midnight.AddHours(3));Check(store.Total(new DateTime(2026,9,21))==total,"Ended sessions must stop");
 var reload=new SessionStore(data);Check(reload.Total(new DateTime(2026,9,20))==10&&!reload.Active,"Persistence and no offline counting");Check(SessionStore.WeekStart(new DateTime(2026,9,20))==new DateTime(2026,9,14),"Monday week boundary");Check(reload.Total(new DateTime(2026,9,1),new DateTime(2026,10,1))==65,"Month total");reload.Theme="fluttershy";reload.Changed();reload.Save();File.WriteAllText(Path.Combine(data,"history.xml"),"broken");var backup=new SessionStore(data);Check(backup.Total(new DateTime(2026,9,20))==10,"Recover atomic backup");
 string broken=Path.Combine(folder,"broken-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(broken);File.WriteAllText(Path.Combine(broken,"history.xml"),"keep this damaged file");var protectedStore=new SessionStore(broken);protectedStore.Start(midnight);protectedStore.End(midnight.AddSeconds(20));Check(File.ReadAllText(Path.Combine(broken,"history.xml"))=="keep this damaged file","Never overwrite unreadable user history");
 File.AppendAllText(log,"PASS: reminder states, partial sessions, rest/pause inclusion, midnight, week/month totals, persistence, end-session, backup recovery, damaged-file protection.\n");
 using(var form=new Reminder(Path.Combine(folder,"ui-"+Guid.NewGuid().ToString("N")),false)){
 form.Show();Application.DoEvents();Snapshot(form,Path.Combine(folder,"main.png"));var mainStore=(SessionStore)Field(form,"store");Call(form,"Toggle");
 for(int selected=0;selected<3;selected++){Call(form,"ToggleOne",selected);double retained=form.States[selected].Left;for(int j=0;j<3;j++){double before=form.States[j].Left;form.States[j].Tick(2);Check(form.States[j].Left==(j==selected?before:before-2),"Independent countdown pause "+selected);}Check(form.States[selected].Left==retained,"Pause preserves time");Call(form,"ToggleOne",selected);}
 Call(form,"ToggleOne",2);double other=form.States[0].Left;((NumericUpDown[])Field(form,"intervals"))[2].Value=51;Check(Math.Abs(form.States[0].Left-other)<1&&form.States[2].Left==3060,"Editing third timer preserves others");((TextBox)Field(form,"customName")).Text="喝水";Check(new SessionStore(mainStore.DirectoryPath).CustomName=="喝水"&&new SessionStore(mainStore.DirectoryPath).CustomMinutes==51,"Custom settings saved");Call(form,"ToggleOne",2);Call(form,"FloatMode");var floating=form.Floating;
 using(var glyph=floating.CenteredGlyph(72)){var b=glyph.GetBounds();Check(Math.Abs(b.Left+b.Width/2-36)<.01,"Glyph horizontal centering");}
 Snapshot(floating,Path.Combine(folder,"bubble.png"));
 form.States[0].Left=0;form.States[1].Left=0;form.States[2].Left=0;Call(form,"Tick");for(int i=0;i<40;i++)Call(floating,"Animate");Check(form.States[0].Phase==1&&form.States[1].Phase==1&&form.States[2].Phase==1,"Simultaneous reminders");float scale=(float)Field(floating,"scale");Check(floating.Width==(int)Math.Round(440*scale),"Compact strip width");Snapshot(floating,Path.Combine(folder,"strip.png"));
 Call(floating,"ClickAt",380f,47f);Check(form.States[0].Phase==2&&form.States[1].Phase==1,"Independent eye action");Call(floating,"ClickAt",380f,82f);Check(form.States[1].Phase==2,"Independent movement action");Call(floating,"ClickAt",380f,117f);Check(form.States[2].Phase==2,"Custom reminder begins rest");Call(floating,"ClickAt",300f,117f);double rest=form.States[2].Left;form.States[2].Tick(2);Check(form.States[2].Left==rest&&form.States[0].Enabled,"Independent float rest pause");Call(floating,"ClickAt",300f,117f);Call(form,"Toggle");Check(!(bool)Field(form,"running")&&mainStore.Active,"Reminder pause does not pause work session");Call(form,"Toggle");form.States[0].Tick(form.States[0].Duration);form.States[1].Tick(form.States[1].Duration);form.States[2].Tick(form.States[2].Duration);Call(form,"Render");Call(floating,"ClickAt",380f,47f);Call(floating,"ClickAt",380f,82f);Call(floating,"ClickAt",380f,117f);for(int i=0;i<40;i++)Call(floating,"Animate");Check(floating.Width==(int)Math.Round(72*scale),"Automatic collapse");
 Call(form,"EndSession");Check(!mainStore.Active,"End work session");var signal=new EventWaitHandle(false,EventResetMode.AutoReset);Reminder.WakeEvent=signal;form.Hide();signal.Set();Call(form,"Tick");Check(form.Visible,"Wake reveals paused hidden window");Reminder.WakeEvent=null;signal.Dispose();
 for(int i=0;i<7;i++)mainStore.AddRange(DateTime.SpecifyKind(DateTime.Today.AddDays(-i).AddHours(9),DateTimeKind.Local).ToUniversalTime(),DateTime.SpecifyKind(DateTime.Today.AddDays(-i).AddHours(10+i),DateTimeKind.Local).ToUniversalTime());
 using(var stats=new StatisticsForm(mainStore,Themes.All[0])){stats.Show();Application.DoEvents();Snapshot(stats,Path.Combine(folder,"week.png"));var mode=(ComboBox)Field(stats,"mode");mode.SelectedIndex=1;Snapshot(stats,Path.Combine(folder,"month.png"));stats.Close();}
 Check(Themes.Ready&&Themes.All.Length==7,"All seven approved themes embedded");
 using(var picker=new ThemePicker(Themes.All[0])){picker.Show();Application.DoEvents();Snapshot(picker,Path.Combine(folder,"characters.png"));picker.Close();}
 foreach(var selected in Themes.All){Call(form,"SetTheme",selected,true);Check(mainStore.Theme==selected.Id&&new SessionStore(mainStore.DirectoryPath).Theme==selected.Id,"Theme selection persists: "+selected.Id);Check(form.Icon==selected.Icon&&form.Floating.BackColor==selected.Bubble,"Theme applies to window and bubble: "+selected.Id);Snapshot(form.Floating,Path.Combine(folder,"bubble-"+selected.Id+".png"));}
 File.AppendAllText(log,"PASS: seven approved role assets, role picker, every role selection persistence, window icon and floating palette synchronization.\n");
 form.ClientSize=new Size(480,700);Call(form,"ArrangeCards");Snapshot(form,Path.Combine(folder,"layout-narrow.png"));Check((int)Field(form,"gridColumns")==1,"Narrow layout single column");
 form.ClientSize=new Size(1400,800);Call(form,"ArrangeCards");Snapshot(form,Path.Combine(folder,"layout-wide.png"));Check((int)Field(form,"gridColumns")==3,"Wide layout three columns");
 foreach(var label in (Label[])Field(form,"counts"))Check(label.Height>=label.GetPreferredSize(Size.Empty).Height,"Countdown text not clipped");
 form.Scale(new SizeF(1.5f,1.5f));form.ClientSize=new Size(1200,900);Call(form,"ArrangeCards");Snapshot(form,Path.Combine(folder,"layout-scale150.png"));foreach(var label in (Label[])Field(form,"counts"))Check(label.Height>=label.GetPreferredSize(Size.Empty).Height,"Scaled countdown not clipped");
 File.AppendAllText(log,"PASS: narrow/wide responsive columns and 150 percent simulated scaled text heights.\n");
 form.Close();}
 foreach(float factor in new[]{1.25f,2f,3f})using(var dpiForm=new Reminder(Path.Combine(folder,"dpi-"+factor),false)){dpiForm.Show();dpiForm.AutoScaleMode=AutoScaleMode.None;var fonts=new System.Collections.Generic.Dictionary<Control,Font>();CaptureFonts(dpiForm,fonts);dpiForm.SuspendLayout();dpiForm.Scale(new SizeF(factor,factor));foreach(var pair in fonts)pair.Key.Font=new Font(pair.Value.FontFamily,pair.Value.Size*factor,pair.Value.Style);dpiForm.ClientSize=new Size((int)(640*factor),(int)(460*factor));dpiForm.ResumeLayout(true);Call(dpiForm,"ArrangeCards");Snapshot(dpiForm,Path.Combine(folder,"layout-font-"+(int)(factor*100)+".png"));foreach(var label in (Label[])Field(dpiForm,"counts"))Check(label.Height>=label.GetPreferredSize(Size.Empty).Height,"Scaled font clipping "+factor);Check((int)Field(dpiForm,"gridColumns")==1,"Scaled narrow column "+factor);dpiForm.Close();}File.AppendAllText(log,"PASS: simulated 125/200/300 percent font and control scaling without countdown clipping.\n");
 string releaseJson="{\"draft\":false,\"prerelease\":false,\"tag_name\":\"v99.0.0\",\"assets\":[{\"name\":\"XieXie-Setup.exe\",\"browser_download_url\":\"https://github.com/peppabaoyu/THANKS/releases/download/v99.0.0/XieXie-Setup.exe\",\"digest\":\"sha256:"+new string('a',64)+"\"}]}";Check(Updates.Parse(releaseJson)!=null,"New update metadata accepted");Check(Updates.Parse(releaseJson.Replace("v99.0.0","v1.0.0"))==null,"Old update ignored");bool badUpdate=false;try{Updates.Parse(releaseJson.Replace("https://github.com/peppabaoyu/THANKS/","https://example.com/"));}catch(InvalidDataException){badUpdate=true;}Check(badUpdate,"Foreign update URL rejected");File.AppendAllText(log,"PASS: newer/older release comparison and foreign update URL rejection.\n");
 File.AppendAllText(log,"PASS: three independently paused countdowns, custom name/settings persistence, editing isolation, three simultaneous reminders, independent rest pause, window render, centered rounded glyph, 440px strip, simultaneous due events, both strip actions, pause includes work time, collapse, stop session, wake hidden window, week/month views.\n");
 }
}
