using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Threading;
using System.Windows.Forms;

static class Setup {
 static readonly string[] Files={"歇歇.exe","歇歇.exe.config","使用说明.html","字体许可.txt"};
 static void Extract(string folder){Directory.CreateDirectory(folder);foreach(string name in Files)using(var input=Assembly.GetExecutingAssembly().GetManifestResourceStream(name)){if(input==null)throw new IOException("安装包内容不完整："+name);using(var output=File.Create(Path.Combine(folder,name)))input.CopyTo(output);}}
 static void StopRunning(){try{using(var signal=EventWaitHandle.OpenExisting("Local\\XieXieExit"))signal.Set();}catch(WaitHandleCannotBeOpenedException){}for(int i=0;i<80;i++){try{using(var signal=EventWaitHandle.OpenExisting("Local\\XieXieExit")){}Thread.Sleep(100);}catch(WaitHandleCannotBeOpenedException){return;}}throw new IOException("请先退出正在运行的歇歇，然后重新安装；你的记录不会被删除。");}
 static void Install(){string directory=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Programs","XieXie");string staging=Path.Combine(Path.GetTempPath(),"XieXie-install-"+Guid.NewGuid().ToString("N"));Extract(staging);StopRunning();Directory.CreateDirectory(directory);string backup=Path.Combine(staging,"backup");Directory.CreateDirectory(backup);foreach(string name in Files){string existing=Path.Combine(directory,name);if(File.Exists(existing))File.Copy(existing,Path.Combine(backup,name));}
 try{foreach(string name in Files)File.Copy(Path.Combine(staging,name),Path.Combine(directory,name),true);}catch{foreach(string name in Files){string old=Path.Combine(backup,name);if(File.Exists(old))File.Copy(old,Path.Combine(directory,name),true);else if(File.Exists(Path.Combine(directory,name)))File.Delete(Path.Combine(directory,name));}throw;}
 string exe=Path.Combine(directory,"歇歇.exe"),desktop=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"歇歇.lnk");Type type=Type.GetTypeFromProgID("WScript.Shell");object shell=Activator.CreateInstance(type);object link=type.InvokeMember("CreateShortcut",BindingFlags.InvokeMethod,null,shell,new object[]{desktop});try{link.GetType().InvokeMember("TargetPath",BindingFlags.SetProperty,null,link,new object[]{exe});link.GetType().InvokeMember("WorkingDirectory",BindingFlags.SetProperty,null,link,new object[]{directory});link.GetType().InvokeMember("IconLocation",BindingFlags.SetProperty,null,link,new object[]{exe+",0"});link.GetType().InvokeMember("Description",BindingFlags.SetProperty,null,link,new object[]{"歇歇 · 三项独立提醒与工作时长"});link.GetType().InvokeMember("Save",BindingFlags.InvokeMethod,null,link,null);}finally{System.Runtime.InteropServices.Marshal.FinalReleaseComObject(link);System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shell);}Directory.Delete(staging,true);Process.Start(new ProcessStartInfo(exe){WorkingDirectory=directory,UseShellExecute=true});}
 [STAThread]static int Main(string[] args){if(args.Length==2&&args[0]=="--verify"){try{Extract(Path.GetFullPath(args[1]));return 0;}catch{return 1;}}if(args.Length==1&&args[0]=="--install"){try{Install();return 0;}catch(Exception ex){MessageBox.Show(ex.Message,"安装未完成");return 1;}}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);using(var form=new Form{Text="安装歇歇 "+Assembly.GetExecutingAssembly().GetName().Version.ToString(3),StartPosition=FormStartPosition.CenterScreen,AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,MaximizeBox=false,FormBorderStyle=FormBorderStyle.FixedDialog,Font=new Font("Microsoft YaHei UI",11)}){var panel=new FlowLayoutPanel{AutoSize=true,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(24),Dock=DockStyle.Fill};panel.Controls.Add(new Label{Text="歇歇 · 给眼睛和身体一点休息",Font=new Font("Microsoft YaHei UI",17,FontStyle.Bold),AutoSize=true});panel.Controls.Add(new Label{Text="• 三项独立提醒，适应窗口大小与显示缩放\n• 七位角色与自己的图片\n• 工作时长统计和 GitHub 更新检查\n\n安装到当前用户，无需管理员权限。\n更新会保存现有记录并关闭旧版，再启动新版。\n不会删除历史统计、设置或上传的图片。",AutoSize=true,Margin=new Padding(3,18,3,18)});var button=new Button{Text="安装 / 更新",AutoSize=true,Padding=new Padding(20,8,20,8),BackColor=Color.FromArgb(255,236,115)};button.Click+=(s,e)=>{button.Enabled=false;try{Install();form.Close();}catch(Exception ex){MessageBox.Show(form,ex.Message,"安装未完成");button.Enabled=true;}};panel.Controls.Add(button);form.Controls.Add(panel);Application.Run(form);}return 0;}
}
