using System;
using System.Drawing;
using System.Windows.Forms;

sealed class StatisticsForm : Form {
 readonly SessionStore store; readonly PonyTheme theme; DateTime anchor=DateTime.Today;
 readonly ComboBox mode=new ComboBox(); readonly Label range=new Label(),total=new Label();readonly DataGridView rows=new DataGridView(); readonly FocusChart chart=new FocusChart();
 public StatisticsForm(SessionStore store,PonyTheme theme){SuspendLayout();AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;this.store=store;this.theme=theme;Text="工作时长 · 周与月";Icon=theme.Icon;Font=new Font("Microsoft YaHei UI",10);BackColor=theme.Page;ForeColor=theme.Ink;StartPosition=FormStartPosition.CenterParent;ClientSize=new Size(680,650);MinimumSize=new Size(580,500);
 var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(22),ColumnCount=1,RowCount=6};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,42));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,38));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,48));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,150));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,45));
 var controls=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false};mode.DropDownStyle=ComboBoxStyle.DropDownList;mode.Items.AddRange(new object[]{"周统计","月统计"});mode.Width=100;mode.SelectedIndex=0;controls.Controls.Add(mode);
 var previous=new Button{Text="上一期",Width=84};previous.Click+=(s,e)=>{anchor=mode.SelectedIndex==0?anchor.AddDays(-7):anchor.AddMonths(-1);RefreshData();};controls.Controls.Add(previous);
 var current=new Button{Text="回到今天",Width=100};current.Click+=(s,e)=>{anchor=DateTime.Today;RefreshData();};controls.Controls.Add(current);
 var next=new Button{Text="下一期",Width=84};next.Click+=(s,e)=>{DateTime candidate=mode.SelectedIndex==0?anchor.AddDays(7):anchor.AddMonths(1);if(candidate.Date<=DateTime.Today)anchor=candidate;else anchor=DateTime.Today;RefreshData();};controls.Controls.Add(next);layout.Controls.Add(controls,0,0);
 range.Dock=DockStyle.Fill;range.Font=new Font(Font,FontStyle.Bold);layout.Controls.Add(range,0,1);total.Dock=DockStyle.Fill;total.Font=new Font("Microsoft YaHei UI",22,FontStyle.Bold);layout.Controls.Add(total,0,2);chart.Dock=DockStyle.Fill;chart.Theme=theme;layout.Controls.Add(chart,0,3);
 rows.Dock=DockStyle.Fill;rows.ReadOnly=true;rows.AllowUserToAddRows=false;rows.AllowUserToDeleteRows=false;rows.AllowUserToResizeRows=false;rows.RowHeadersVisible=false;rows.BackgroundColor=Color.White;rows.BorderStyle=BorderStyle.None;rows.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;rows.SelectionMode=DataGridViewSelectionMode.FullRowSelect;rows.Columns.Add("date","日期");rows.Columns.Add("time","工作时长");rows.ColumnHeadersHeight=35;rows.RowTemplate.Height=30;rows.EnableHeadersVisualStyles=false;rows.ColumnHeadersDefaultCellStyle.BackColor=theme.Bubble;rows.ColumnHeadersDefaultCellStyle.ForeColor=theme.Ink;rows.DefaultCellStyle.SelectionBackColor=theme.Page;rows.DefaultCellStyle.SelectionForeColor=theme.Ink;layout.Controls.Add(rows,0,4);
 layout.Controls.Add(new Label{Text="包含暂停、起身休息与等待确认。周统计按周一至周日计算。",Dock=DockStyle.Fill,Padding=new Padding(0,12,0,0)},0,5);Controls.Add(layout);mode.SelectedIndexChanged+=(s,e)=>RefreshData();RefreshData();ResumeLayout(true);}
 public void RefreshData(){DateTime start=mode.SelectedIndex==0?SessionStore.WeekStart(anchor):new DateTime(anchor.Year,anchor.Month,1);DateTime end=mode.SelectedIndex==0?start.AddDays(7):start.AddMonths(1);range.Text=mode.SelectedIndex==0?start.ToString("yyyy.MM.dd")+" — "+end.AddDays(-1).ToString("MM.dd"):start.ToString("yyyy 年 M 月");total.Text=SessionStore.Duration(store.Total(start,end));rows.Rows.Clear();int count=(int)(end-start).TotalDays;double[] values=new double[count];for(int i=0;i<count;i++){DateTime d=start.AddDays(i);values[i]=store.Total(d);rows.Rows.Add(d.ToString("MM/dd ddd"),SessionStore.Duration(values[i]));}chart.Values=values;chart.First=start;chart.Invalidate();}
}
sealed class FocusChart : Control {
 public double[] Values=new double[0];public DateTime First;public PonyTheme Theme;
 public FocusChart(){DoubleBuffered=true;}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);if(Values.Length==0)return;Graphics g=e.Graphics;g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;double max=1;foreach(double value in Values)max=Math.Max(max,value);float left=10,baseY=Height-32,space=(Width-20f)/Values.Length;using(var bar=new SolidBrush(Theme.Accent))using(var empty=new SolidBrush(Theme.Bubble))using(var ink=new SolidBrush(Theme.Ink))using(var font=new Font("Microsoft YaHei UI",9))using(var format=new StringFormat{Alignment=StringAlignment.Center}){for(int i=0;i<Values.Length;i++){float h=(float)(Values[i]/max*(Height-53));float x=left+space*i+space*.19f;g.FillRectangle(Values[i]>0?bar:empty,x,baseY-Math.Max(3,h),space*.62f,Math.Max(3,h));if(Values.Length<=7 || i%5==0 || i==Values.Length-1)g.DrawString(First.AddDays(i).Day.ToString(),font,ink,new RectangleF(left+space*i,baseY+6,space,23),format);}if(max<=1)g.DrawString("还没有记录，开始本次工作后会自动累计",font,ink,new RectangleF(0,15,Width,32),format);}}
}
